version: "3"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - redis
    volumes:
      - ./download-data/:/opts/download-data/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - "5601:5601"
  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./download-data/:/opts/download-data/
  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
  database:
    image: postgres
    ports:
      - "6789:5432"
    env_file:
      - database.env
    volumes:
      - ./database-data/:/var/lib/postgresql/data/
